#----------------------
# To be changed
#----------------------
BIN = Factory

SOURCE := \
	Product.cpp \
	Product.h \
	Factory.cpp \
	Factory.h \
	main.cpp

#----------------------
# Do not change
#----------------------
CC = g++

all: $(BIN)

$(BIN): $(SOURCE)
	$(CC) $(SOURCE) -o $(BIN)

clean:
	rm -f $(BIN)

#----------------------
