#----------------------
# To be changed
#----------------------
BIN = Adapter

SOURCE := \
	Adapter.cpp \
	Adapter.h \
	main.cpp

#----------------------
# Do not change
#----------------------
CC = g++

all: $(BIN)

$(BIN): $(SOURCE)
	$(CC) $(SOURCE) -o $(BIN)

clean:
	rm -f $(BIN)

#----------------------
