#----------------------
# To be changed
#----------------------
BIN = Bridge

SOURCE := \
	Abstraction.cpp \
	Abstraction.h \
	AbstractionImp.cpp \
	AbstractionImp.h \
	main.cpp

#----------------------
# Do not change
#----------------------
CC = g++

all: $(BIN)

$(BIN): $(SOURCE)
	$(CC) $(SOURCE) -o $(BIN)

clean:
	rm -f $(BIN)

#----------------------
